version: '3.4'

services:
    apache:
        build:
            context: ./
            dockerfile: Dockerfile
        #ports:
        #    - "80:80"
        volumes:
            - sources:/var/www:rw
            - ./docker/vhost.d:/etc/apache2/sites-enabled
        environment:
            - XDEBUG_CONFIG=remote_host=172.0.0.1 remote_enable=on
            - APP_XDEBUG=enabled
            - COMPOSER_AUTH=${COMPOSER_AUTH}
            - VIRTUAL_HOST=youtube.like.test
            - VIRTUAL_PORT=80
        depends_on:
            - db
        links:
            - db:db
            - mail:mail
        env_file:
            - .env
        logging:
            driver: "json-file"
            options:
                max-size: "1M"
                max-file: "5"

    db:
        image: mysql:8
        command: [mysqld, --default-authentication-plugin=mysql_native_password]
        volumes:
            - database:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: "toor"
            MYSQL_USER: "youtube"
            MYSQL_PASSWORD: "google"
            MYSQL_DATABASE: "youtube_like"
        ports:
            - "3306:3306"

    mail:
        image: djfarrelly/maildev
        expose:
            - 8080
        environment:
            - VIRTUAL_HOST=mailer-dev.local.dev
            - VIRTUAL_PORT=80

volumes:
    database: ~
    sources:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD

networks:
    default:
        external:
            name: nginx-proxy
