#!/usr/bin/env bash

GIT_DIR=${GIT_DIR-`git rev-parse --git-dir`}
. "$GIT_DIR/hooks/change_detector.sh"

junkchecker_phrases_file="$GIT_DIR/hooks/junk-words"
if [ -f $junkchecker_phrases_file ]
then
	for FILE in $(git diff-index --cached --name-status HEAD -- | cut -c 3-); do
		if [ -f "$FILE" ]
		then
			while IFS='' read -r line || [[ -n "$line" ]];
			do
				git diff --cached --diff-filter=ACMR "$FILE" | grep -E '^\+' | grep --quiet "$line"
				if [ $? -eq 0 ]
				then
					cat <<- EOT >&2
					Junk checker detected: $FILE contains '$line'.
					Use the --no-verify option to bypass this error message.
					EOT
					exit 1
				fi
			done < "$junkchecker_phrases_file"
		fi
	done
else
	echo "Could not find file $junkchecker_phrases_file . Please check your configuration."
	exit 2
fi

if has_changed pre-commit composer.json
then
    source ./.autoaliases.sh
	composer -q validate
	isValid=$?
	if [ $isValid -ne 0 ]
	then
		exit $isValid
	fi
fi
