name: Migration checker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  migration_checker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run migration checker
      run: docker network create nginx-proxy && make start && make migrate
